<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-PQ7IP8FG" failures="1" tests="1" name="Default test" time="9.012" errors="0" timestamp="2024-08-03T03:37:44 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="8.392">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;THANKYOU FOR THE ORDER.&amp;gt; but was:&amp;lt;Thankyou for the order.&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<THANKYOU FOR THE ORDER.> but was:<Thankyou for the order.>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:125)
at saloni.stepDefinition.stepDefinitionimpl.message_is_displayed_on_confirmation_page(stepDefinitionimpl.java:59)
at âœ½."Thankyou for the order." message is displayed on confirmationPage(file:///C:/Users/saloni%20jain/eclipse-workspace/projectfarmework/src/test/java/cucumber/PurchaseOrder.feature:32)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
